name = "kirlia"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "kirlia.bluehat358.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.kirlia.bluehat358.biz.id", custom_domain = true },
  { pattern = "df.game.naver.com.kirlia.bluehat358.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.kirlia.bluehat358.biz.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.kirlia.bluehat358.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.kirlia.bluehat358.biz.id", custom_domain = true },  
  { pattern = "cache.netflix.com.kirlia.bluehat358.biz.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.kirlia.bluehat358.biz.id", custom_domain = true },
  { pattern = "img.email1.vidio.com.kirlia.bluehat358.biz.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "kirlia"
id = "550470a19aa14d338e4c7d8b03f40a73"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "0e354017-c2d8-47dd-9c52-841d125e7358"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/sub.html"
